# Generated by Django 4.1.1 on 2022-09-25 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('create_date', models.DateTimeField(verbose_name='create_date')),
                ('nombres', models.CharField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=45, verbose_name='apellidos')),
                ('telefono', models.CharField(max_length=30, verbose_name='telefono')),
                ('numero_celular', models.CharField(max_length=30, verbose_name='numero_celular')),
                ('correo', models.EmailField(max_length=100, verbose_name='correo')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='tipo_documento')),
                ('numero_documento', models.CharField(max_length=100, verbose_name='numero_documento')),
                ('direccion', models.CharField(max_length=45, verbose_name='direccion')),
                ('rol', models.CharField(choices=[('MEDICO', 'Med'), ('ENFERMER@', 'Enf'), ('PACIENTE', 'Pac'), ('FAMILIAR', 'Fam'), ('AUXILIAR', 'Aux')], default='PACIENTE', max_length=45)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(verbose_name='create_date')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_auxiliar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rh', models.CharField(max_length=45)),
                ('especialidad', models.CharField(max_length=45)),
                ('auxiliar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfermero', to='app.auxiliar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('tipo_documento', models.CharField(max_length=45)),
                ('numero_documento', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('numero_celular', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('parentezco', models.CharField(max_length=45)),
                ('auxiliar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='app.auxiliar')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('especializacion', models.CharField(max_length=45)),
                ('rh', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(verbose_name='create_date')),
                ('auxiliar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='app.auxiliar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('departamento', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('estado_civil', models.CharField(max_length=10)),
                ('ocupacion', models.CharField(max_length=45)),
                ('etnia', models.CharField(max_length=45)),
                ('rH', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('enfermedades_hereditarias', models.CharField(max_length=10)),
                ('numero_embarazos', models.IntegerField(default=0)),
                ('numero_abortos', models.IntegerField(default=0)),
                ('numero_operaciones', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(verbose_name='create_date')),
                ('auxiliar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='app.auxiliar')),
                ('enfermero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='app.enfermero')),
                ('familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='app.familiar')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='app.medico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sugerencia', models.CharField(max_length=200)),
                ('fecha_registro', models.DateField()),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='app.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Signos_vitales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=45)),
                ('frecuencia_respiratoria', models.CharField(max_length=45)),
                ('frecuencia_cardiaca', models.CharField(max_length=45)),
                ('temperatura', models.CharField(max_length=45)),
                ('presion_arterial', models.CharField(max_length=45)),
                ('glicemias', models.CharField(max_length=45)),
                ('fecha_registro', models.DateField()),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('prioridad', models.CharField(max_length=45)),
                ('fecha_registro', models.DateField()),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='app.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='app.paciente')),
            ],
        ),
    ]
