from .user import User
from .auxiliar import Auxiliar
from .enfermero import Enfermero
from .medico import Medico
from .paciente import Paciente
from .familiar import Familiar
from .diagnosticos import Diagnostico
from .signos_vitales import Signos_vitales
from .sugerencias import Sugerencias